version: '3.2'
services:

  mongo.dev:
    container_name: mongo.dev
    image: mongo:3.4
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - bubble

  backend.dev:
    container_name: backend.dev
    volumes:
      - ./backend:/backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - bubble

networks:
  bubble:
    external: true

volumes:
  mongo:
